// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpqIYiBjv59nc2S1Zij14ujG6AhqLlF44',
    appId: '1:101704024650:web:5198be9374fc1727589cb3',
    messagingSenderId: '101704024650',
    projectId: 'taskermg-e2001',
    authDomain: 'taskermg-e2001.firebaseapp.com',
    storageBucket: 'taskermg-e2001.appspot.com',
    measurementId: 'G-B1RS2CVFFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGSF0ew2ivWs2Ycghuqf2-h1Fuf9ws88U',
    appId: '1:101704024650:android:0c04cd6abb99a837589cb3',
    messagingSenderId: '101704024650',
    projectId: 'taskermg-e2001',
    storageBucket: 'taskermg-e2001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-Rj0OEE0FwxIxBDRWbPufA1VOSCwFAFY',
    appId: '1:101704024650:ios:0dd0cba36bd4dbc5589cb3',
    messagingSenderId: '101704024650',
    projectId: 'taskermg-e2001',
    storageBucket: 'taskermg-e2001.appspot.com',
    iosBundleId: 'com.example.uno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-Rj0OEE0FwxIxBDRWbPufA1VOSCwFAFY',
    appId: '1:101704024650:ios:0dd0cba36bd4dbc5589cb3',
    messagingSenderId: '101704024650',
    projectId: 'taskermg-e2001',
    storageBucket: 'taskermg-e2001.appspot.com',
    iosBundleId: 'com.example.uno',
  );
}
